// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wntniqpfmuqaidpuoknf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudG5pcXBmbXVxYWlkcHVva25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Njg3NDYsImV4cCI6MjA2NjQ0NDc0Nn0.WcuFFfw3EVG-vlNa3szLIKeyUDfX2zeIfrQ-S8xQSqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);